### PR TITLE
fix(ui5-busyindicator): fixed aria-labelledby value

### LINKED ISSUE #3256: BusyIndicator: ARIA attribute element ID does not exist on the page: aria-labelledby="ui5wc_XXX-label"
**Describe the bug**
Ensures all ARIA attributes have valid values

**Isolated Example**
https://g00py.csb.app/

**To Reproduce**
1. Go to 'https://g00py.csb.app/'
2. Open chrome element inspect or open the Chrome plugin axe-coconut
3. check the label id from aria-labelledby attribute

**Expected behavior**
Ensures all ARIA attributes have valid values

**Screenshots**
image

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.14
`@ui5/webcomponents-react` version: 0.15.4
Operating System: Mac OS
Browser: Chrome

**Additional context**
I am from SAP Successfactors

### PR DESCRIPTION
**Pull request by TeodorTaushanov**
Fixes #3256

### CODE REVIEW

File: packages/main/src/BusyIndicator.js [hunk 1]
```diff
@@ -174,6 +174,10 @@ class BusyIndicator extends UI5Element {
 		return this.i18nBundle.getText(BUSY_INDICATOR_TITLE);
 	}
 
+	get labelId() {
+		return this.text ? this._id + "-label" : undefined;
```
Comment (ilhan007) [inline packages/main/src/BusyIndicator.js:178]: use "`${this._id}-label`", instead of string concatenation.

**Review by ilhan007 — APPROVED** [review]

**Review by dimovpetar — APPROVED** [review]
