### PR TITLE
fix(ui5-busyindicator): prevent keyboard events propagation to controls

### LINKED ISSUE #1598: Busy Indicator: children can receive keyboard event error
**Describe the bug**
when as  children of `Busy Indicator,  children should to block the keyboard event.  but now the children still can receive keyboard event.

**To reproduce**

`<ui5-busyindicator active size="Small">`
  `    <ui5-button design="Default">Enabled</ui5-button>`
 `     <ui5-button design="Default">Enabled</ui5-button>`
`</ui5-busyindicator>`

image

### PR DESCRIPTION
**Pull request by fifoosid**
Fixes #1598

### CODE REVIEW

File: packages/main/src/BusyIndicator.js [hunk 1]
```diff
@@ -97,6 +97,23 @@ class BusyIndicator extends UI5Element {
 		this.i18nBundle = getI18nBundle("@ui5/webcomponents");
 	}
 
+	onEnterDOM() {
```
Comment (ilhan007) [inline packages/main/src/BusyIndicator.js:100]: We can also set tabindex="-1" for this case on the host and it should remove the content of the busy from the tab chain.

File: packages/main/src/BusyIndicator.js [hunk 2]
```diff
@@ -97,6 +97,23 @@ class BusyIndicator extends UI5Element {
...
+		this._preventHandler = this._preventEvent.bind(this);
```
Comment (vladitasev) [inline packages/main/src/BusyIndicator.js:101]: You can move this line to the constructor

File: packages/main/src/BusyIndicator.js (hunk 1 above)
Comment (fifoosid) [reply packages/main/src/BusyIndicator.js]: We added it because it covers another case, but it is not enough.
