### PR TITLE
fix(ui5-navigation-layout): resolve mobile phone display issues in landscape mode

### LINKED ISSUE #12913: [ui5-side-navigation]: new responsiveness - issue
### Bug Description

When phone is in landscape mode, the collapsed Side Navigation opens Responsive popover as full screen dialog and Menu, that is fillscreen. This is inconsistent and should be fixed.
Also there are issues when selecting item from the menu.
Interaction design is changed for phone and the issue is illustrated also in Figma.

### Affected Component

_No response_

### Expected Behaviour

_No response_

### Isolated Example

_No response_

### Steps to Reproduce

1.
2.
3.
...

### Log Output, Stack Trace or Screenshots

_No response_

### Priority

None

### UI5 Web Components Version

latest

### Browser

Chrome

### Operating System

_No response_

### Additional Context

_No response_

### Organization

_No response_

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

### PR DESCRIPTION
**Pull request by TeodorTaushanov**
On mobile phone devices, the layout is now consistently set to small size, irrespective of the device's size.

fixes #12913

### CODE REVIEW

File: packages/fiori/src/NavigationLayout.ts [hunk 1]
```diff
@@ -28,9 +29,9 @@ const SCREEN_WIDTH_BREAKPOINT = 600;
  *
  * ### Responsive Behavior
  *
- * On larger screens (screen width of 600px or more), the side navigation is visible
+ * On larger screens with a width of 600px or more, excluding phones, the side navigation is visible
```
Comment (Stoev) [inline packages/fiori/src/NavigationLayout.ts]:
```suggestion
 * On larger screens with a width of 600px or more, excluding mobile phone devices, the side navigation is visible
```

File: packages/fiori/src/NavigationLayout.ts [hunk 2]
```diff
@@ -28,9 +29,9 @@ const SCREEN_WIDTH_BREAKPOINT = 600;
...
  * by default and can be expanded or collapsed using the `mode` property.
- * On small screens (screen width of 599px or less), the side navigation is hidden by
+ * On phone devices and screens with a width of 599px or less, the side navigation is hidden by
```
Comment (Stoev) [inline packages/fiori/src/NavigationLayout.ts]:
```suggestion
 * On mobile phone devices and screens with a width of 599px or less, the side navigation is hidden by
```

**Review by Stoev — COMMENTED** [review]
fix(ui5-navigation-layout): resolve mobile phone display issues in landscape mode #12900

On mobile phone devices, the layout is now consistently set to small size, irrespective of the device's size.

JIRA: BGSOFUIRODOPI-3570
