### PR TITLE
fix(scroll enablement): fix scrolling issue on scroll & mobile

### LINKED ISSUE #1531: ui5-wheel-slider: dragging the slider makes it rotate very fast
This is a new feature, not present in RC6. Upon merging this, it worked fine. The user was able to drag with the mouse or thumb (on mobile) properly.

It seems some commit broke this, since now dragging makes the wheel spin very fast. 
Please check commit history and find out what went wrong.

### PR DESCRIPTION
**Pull request by fifoosid**
Fixes #1531

### CODE REVIEW

File: packages/base/src/delegate/ScrollEnablement.js [hunk 1]
```diff
@@ -15,6 +15,16 @@ class ScrollEnablement extends EventProvider {
 
 		this.isPhone = isPhone();
 
+		// On Android devices touchmove is thrown one more time than neccessary (together with touchend)
+		// so we have to cache the previus coordinates in order to provide correct parameters in the
+		// event for Android
+		this.cashedValue = {};
```
Comment (vladitasev) [inline packages/base/src/delegate/ScrollEnablement.js:21]: cached

File: packages/base/src/delegate/ScrollEnablement.js [hunk 2]
```diff
@@ -94,9 +108,21 @@ class ScrollEnablement extends EventProvider {
...
+		this.cashedValue.dragX = this._prevDragX;
+		this.cashedValue.dragY = this._prevDragY;
+
+		this._prevDragX = dragX;
+		this._prevDragY = dragY;
 	}
 
 	ontouchend(event) {
+		if (this.isPhone
+			&& (Math.abs(event.changedTouches[0].pageX - this.startX) < 10
```
Comment (vladitasev) [inline packages/base/src/delegate/ScrollEnablement.js:121]: const deltaX = Math.abs(event.changedTouches[0].pageX - this.startX;
const deltaY = .......
and simplify the expression
