### PR TITLE
fix(ui5-input): focus is handled properly

### LINKED ISSUE #2652: Input Suggestions are not shown in Dialog on first focus.
**Describe the bug**
<ui5-input show-suggestions ></ui5-input> controls is not showing suggestion in a dialog first time.
If ui5-input is the first control in a dialog and is auto focused then suggestions are not shown. When focus is moved out first and 
then focus ui5-input back, then the suggestions are showing up.

**To reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-6elmf?file=/index.html
2. Click "Open Dialog"
3. When dialog opens, focus will be on the input element, type "ca" and see no suggestions is shown.
4. Now click outside ui5-input box and click back to ui5-input.  Once you get focus back to ui5-input, type "ca", you should see suggetions

**Isolated example**
[CodeSandbox](https://codesandbox.io/s/ui5-webco mponents-forked-6elmf?file=/index.html)

**Expected behavior**
Once user open Dialog and ui5-input field is auto focused, then the suggestions should be shown.

**Context**
- UI5 Web Components version: 0.29.0
- OS/Platform: any
- Browser *(if relevant)*: any
- Other information: Input suggestion was working with version v0.23.6 as expected, but with latest versions(0.27.0 and above) it is not working

**Organization:** *(if applicable)*
Success Factors

**Priority:** *(optional)* *High*

### PR DESCRIPTION
**Pull request by niyap**
Previously, on focus the ui5-input component, when the event target was ui5-input, the focused attribute was not added. As a result, the focus outline was not presented, as well as the suggestions were not visualised initially when used.

Fixes #2652

### CODE REVIEW

File: packages/main/src/MultiInput.js [hunk 1]
```diff
@@ -237,6 +237,18 @@ class MultiInput extends Input {
 		}
 	}
 
+	/**
+	 * @override
```
Comment (MapTo0) [inline packages/main/src/MultiInput.js:241]: override?

**Review by MapTo0 — CHANGES_REQUESTED** [review]
add a test reproducing the described issue

I think the issue is now just moved in the multi input

File: packages/main/test/specs/Input.spec.js [hunk 2]
```diff
@@ -371,4 +371,19 @@ describe("Input general interaction", () => {
 		assert.notOk(inputPopover.isDisplayedInViewport(), "The inpuit popover is closed as it lost the focus.");
 		assert.ok(helpPopover.isDisplayedInViewport(), "The help popover remains open as the focus is within.");
 	});
+
+	it("Should open suggestions popover when ui5-input is the fisrt focusable element within a dialog", () => {
```
Comment (ilhan007) [inline packages/main/test/specs/Input.spec.js:375]: first (typo)

**Review by ilhan007 — APPROVED** [review]

**Review by ilhan007 — APPROVED** [review]
it is ok to me, up to @MapTo0 to merge the change

**Review by MapTo0 — APPROVED** [review]
