### PR TITLE
fix(ui5-popover): fix horizontal placement (Start and End) in rtl mode

### LINKED ISSUE #12603: [ui5-popover]: incorrect usage of `placement` inside project
### Bug Description

Many places in the project use `this.effectiveDir` and check for RTL to set either `placement="Start"` or `placement="End"` which is incorrect - Start and End already account for RTL. This is probably a leftover from 1.x where Left/Right were used instead.

Example of incorrect usage - `ShellBar.ts`

Please check if all occurrences are using the correct placement.

### PR DESCRIPTION
**Pull request by TeodorTaushanov**
fix horizontal placement (Start and End) in rtl mode
fix usage of `placement` and `horizontalAlign` properties in the framework
add new PopoverActualHorizontalAlign and PopoverActualPlacement enums

fixes #12603

### CODE REVIEW

File: packages/main/src/Popover.ts [hunk 1]
```diff
@@ -710,12 +710,20 @@ class Popover extends Popup {
...
-		let actualPlacement = placement;
-		const isVertical = placement === PopoverPlacement.Top
-			|| placement === PopoverPlacement.Bottom;
+		let placement = this.placement;
+		const isVertical = placement === PopoverPlacement.Top || placement === PopoverPlacement.Bottom;
 		const popoverSize = this.getPopoverSize(!this.allowTargetOverlap);
 
+		if (this.isRtl) {
+			if (placement === PopoverPlacement.Start) {
+				placement = PopoverPlacement.End;
```
Comment (pskelin) [inline packages/main/src/Popover.ts]: Start means start regardless of RTL, I find this confusing. Maybe you want to use Left/Right here? the switch statement below also uses Top/Bottom, which are actual directions and not logical directions.

Comment (TeodorTaushanov) [reply packages/main/src/Popover.ts]: The method is called `getActualPlacement` and we need to calc the actual placement depending on rtl and whether there is a place at the specified placement.

Top/Bottom is another question for another time.

**Review by pskelin — APPROVED** [review]

File: packages/main/src/MenuItem.ts
Comment (dimovpetar) [inline packages/main/src/MenuItem.ts:1]: MenuItem.css has selector that relies on the old actual placement:
```css
.ui5-menu-rp.ui5-menu-rp-sub-menu[actual-placement="Start"] {
	margin-top: 0.25rem;
	margin-inline: var(--_ui5_menu_submenu_placement_type_left_margin_offset);
}
```
 Check if this can be removed.

File: packages/main/src/Popover.ts
Comment (dimovpetar) [inline packages/main/src/Popover.ts]: Incorporate ActualHorizontalAlign enum with values "Left", "Right", "Center" and "Stretch". Can be done in another PR

File: packages/main/src/MenuItem.ts
Comment (TeodorTaushanov) [reply packages/main/src/MenuItem.ts:1]: Currently this does nothing. Removed.

File: packages/main/src/Popover.ts
Comment (TeodorTaushanov) [reply packages/main/src/Popover.ts]: Done.

**Review by dimovpetar — APPROVED** [review]
