### PR TITLE
fix(ui5-popover): clicking on iframe now closes an open popover

### LINKED ISSUE #6087: Popover not getting closed when focus is lost
### **Bug Description**
The popover is not getting closed when focus is moved to another window (e.g clicking in an iframe).

### **Expected Behavior**
Popover gets closed when focus is lost

### **Steps to Reproduce**
URL: https://codesandbox.io/s/red-meadow-2uip40

1. Open the Popover
2. Click on the iframe => not getting closed
3. Click somewhere else on the page => popover is closed.

### **Isolated Example**
URL: https://codesandbox.io/s/red-meadow-2uip40

### **Context**
- UI5 Web Components version: latest
- OS/Platform: any
- Browser: any
- Affected component: `ui5-popover` and all static area templates using popover (select, input, etc)

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [] Medium
- [x ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

### PR DESCRIPTION
**Pull request by gmkv**
The `click` event on an iframe element does not fire on the parent document that embeds it.

With this change, the logic handling closing of popovers now also relies on the document losing focus.
If an iframe element is focused, then the popover gets closed.

Fixes #6087

### CODE REVIEW

File: packages/base/src/util/PopupUtils.ts [hunk 1]
```diff
@@ -59,13 +59,13 @@ const isClickInRect = (event: MouseEvent | TouchEvent, rect: DOMRect) => {
 	let x;
 	let y;
 
-	if (event instanceof TouchEvent) {
+	if (event instanceof MouseEvent) {
```
Comment (gmkv) [inline packages/base/src/util/PopupUtils.ts:62]: `TouchEvent` is undefined in Firefox desktop. All other browsers mock its existence, even if they don't have a touch screen.

**Review by TeodorTaushanov — APPROVED** [review]
