### PR TITLE
fix(framework): fix find first focusable element

### LINKED ISSUE #10965: [ui5-popup]: First focusable element is not located correctly
### Bug Description

In Popup.ts - getFisrtFocusableElement is not optimized to search in depth but searches sibling first.

### Affected Component

ui5-popover, ui5-responsive-popover, ui5-dialog 

### Expected Behaviour

Focus should go on "Item 3", instead it focuses the first focusable element which is on a higher node level.

### Isolated Example

https://js-wensajc5.stackblitz.io/

### Steps to Reproduce

1. open https://js-wensajc5.stackblitz.io/
2. Click the menu button
3. Select "Item 3"
4. Click  menu button again

### Log Output, Stack Trace or Screenshots

_No response_

### Priority

High

### UI5 Web Components Version

2.7.3

### Browser

Chrome

### Operating System

_No response_

### Additional Context

_No response_

### Organization

_No response_

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

### PR DESCRIPTION
**Pull request by TeodorTaushanov**
fixes #10965

### CODE REVIEW

**Review by dimovpetar — CHANGES_REQUESTED** [review]
Also add dedicated tests, maybe in new file FocusableElements.cy.tsx

File: packages/base/src/util/FocusableElements.ts [hunk 1]
```diff
@@ -36,6 +36,17 @@ const isElemFocusable = (el: HTMLElement) => {
 	return el.hasAttribute("data-ui5-focus-redirect") || !isElementHidden(el);
 };
 
+const isUI5ElementWithNegativeTabIndex = (el: HTMLElement) => {
```
Comment (nnaydenow) [inline packages/base/src/util/FocusableElements.ts:39]: why do we need this?

File: packages/base/src/util/FocusableElements.ts [hunk 2]
```diff
@@ -36,6 +36,17 @@ const isElemFocusable = (el: HTMLElement) => {
...
+	if (instanceOfUI5Element(el)) {
+		const tabIndex = el.getAttribute("tabindex");
+		if (tabIndex !== null && tabIndex !== undefined && parseInt(tabIndex) < 0) {
```
Comment (nnaydenow) [inline packages/base/src/util/FocusableElements.ts:42]: getAttribute returns null or string. check with undefined is redundant

File: packages/base/src/util/FocusableElements.ts (hunk 1 above)
Comment (TeodorTaushanov) [reply packages/base/src/util/FocusableElements.ts:39]: This covers `<ui5-input tabindex="-1"></ui5-input>`, which is used in the FileUploader component.

**Comment by TeodorTaushanov** [comment]
> Also add dedicated tests, maybe in new file FocusableElements.cy.tsx

Done.

File: packages/fiori/test/pages/FocusableElements.html
Comment (dimovpetar) [inline packages/fiori/test/pages/FocusableElements.html:1]: Move this file to the base package

File: packages/base/cypress/specs/util/FocusableElements.cy.tsx [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+					</SideNavigation>
+					<br/>
+					<Button id="buttonId">Close</Button>
+				</div>
+			</>
+		);
+
+		// wait for item navigation to set tabindex
+		// eslint-disable-next-line cypress/no-unnecessary-waiting
+		cy.wait(100);
```
Comment (dimovpetar) [inline packages/base/cypress/specs/util/FocusableElements.cy.tsx:37]: Better replace it with:
```ts
	cy.get("#subItem1")
			.shadow()
			.find(".ui5-sn-item")
			.should("have.attr", "tabindex", "0");
```

**Review by dimovpetar — CHANGES_REQUESTED** [review]

File: packages/fiori/test/pages/FocusableElements.html
Comment (TeodorTaushanov) [reply packages/fiori/test/pages/FocusableElements.html:1]: Base library doesn't have dependency to the Fiori library.

**Review by dimovpetar — APPROVED** [review]

**Review by nnaydenow — APPROVED** [review]
