### PR TITLE
fix(ui5-side-navigation): focus is correct after selecting overflow item

### LINKED ISSUE #11511: [Side Navigation]: focus is lost after selecting overflow item
### Bug Description

When you click to select some item that is in the overflow menu, once it moves to the actual side navigation in collapsed mode, focus should return to it. Instead the focus is lost

### Affected Component

ui5-side-navigation

### Expected Behaviour

_No response_

### Isolated Example

https://sap.github.io/ui5-webcomponents/nightly/packages/fiori/test/pages/SideNavigation.html

### Steps to Reproduce

1. Open the side navigation in collapsed mode
2. Click on the '...' to open the overflow menu
3. Select some item -> It moves to the main navigation
4. Focus is lost instead of being on the recently selected item

### Log Output, Stack Trace or Screenshots

_No response_

### Priority

Medium

### UI5 Web Components Version

latest

### Browser

Chrome

### Operating System

_No response_

### Additional Context

_No response_

### Organization

SAP

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

### PR DESCRIPTION
**Pull request by TeodorTaushanov**
Focus returns to the selected navigation item when the overflow menu is closed.

fixes #11511

### CODE REVIEW

**Comment by TeodorTaushanov** [comment]
> Please consider:
> 
> fix(ui5-side-navigation): focus is correct after selecting overflow item
> 
> Is additional explanation necessary, for example: Focus returns to the selected navigation item when the overflow menu is closed.

Done.

**Review by Stoev — COMMENTED** [review]
Looks good.

File: packages/fiori/src/SideNavigation.ts [hunk 1]
```diff
@@ -289,6 +290,23 @@ class SideNavigation extends UI5Element {
...
+
+	_onMenuClose() {
+		const menu = this.getOverflowPopover();
+		if (!menu._popover.preventFocusRestore) {
+			return;
+		}
+
+		const selectedItem = this._findSelectedItem(this.items as Array<SideNavigationItem | SideNavigationGroup>);
+
+		// const selectedItem = this._flexibleItemNavigation._getCurrentItem();
```
Comment (LidiyaGeorgieva) [inline packages/fiori/src/SideNavigation.ts]: delete this

**Review by LidiyaGeorgieva — APPROVED** [review]
