### PR TITLE
fix(ui5-slider): up and down arrow behavior in RTL mode

### LINKED ISSUE #9967: [ui5-slider]: Arrow Up and Down do not change properly the value in RTL mode
### Bug Description

When slider is in RTL mode the Arrow Up should move the slider to the left to the bigger values, and Arrow Down should move the slider to the right. It is the expected behavior and how the native input of type "range" is working. 
At the moment Arrow Up moves the slider to the right in both RTL and LTR mode.

### Affected Component

ui5-slider

### Expected Behaviour

_No response_

### Isolated Example

_No response_

### Steps to Reproduce

1. Open https://sap.github.io/ui5-webcomponents/nightly/packages/main/test/pages/Slider.html
2. Go to RTL example
3. Try to change the value by using Arrow Up and Arrow Down keys
...

### Log Output, Stack Trace or Screenshots

_No response_

### Priority

None

### UI5 Web Components Version

2.0.1

### Browser

Chrome

### Operating System

_No response_

### Additional Context

_No response_

### Organization

_No response_

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

### PR DESCRIPTION
**Pull request by nikoletavnv**
Fixes #9967

### CODE REVIEW

File: packages/main/src/SliderBase.ts [hunk 1]
```diff
@@ -635,11 +633,19 @@ abstract class SliderBase extends UI5Element {
 		return isUpAction ? step : step * -1;
 	}
 
-	static _isDecreaseValueAction(e: KeyboardEvent) {
+	static _isDecreaseValueAction(e: KeyboardEvent, directionStart: DirectionStart) {
```
Comment (Okiana) [inline packages/main/src/SliderBase.ts:636]: I was not able to find this function to be called anywhere in the project. I've tested in the test page to put breakpoint in it and aslo it's not called. Do we still need it?

**Review by Okiana — APPROVED** [review]

**Review by nnaydenow — APPROVED** [review]
